//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cnf_holidays
    {
        public decimal id { get; set; }
        public decimal location_id { get; set; }
        public decimal year { get; set; }
        public System.DateTime holiday_date { get; set; }
        public string holiday { get; set; }
    
        public virtual cnf_locations cnf_locations { get; set; }
    }
}
