//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cnf_user_category_mapping
    {
        public decimal id { get; set; }
        public string username { get; set; }
        public decimal category_id { get; set; }
    
        public virtual cnf_categories cnf_categories { get; set; }
        public virtual cnf_users cnf_users { get; set; }
    }
}
