//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hackathon2019Entities : DbContext
    {
        public hackathon2019Entities()
            : base("name=hackathon2019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cnf_categories> cnf_categories { get; set; }
        public virtual DbSet<cnf_holidays> cnf_holidays { get; set; }
        public virtual DbSet<cnf_locations> cnf_locations { get; set; }
        public virtual DbSet<cnf_users> cnf_users { get; set; }
        public virtual DbSet<item_utilisation> item_utilisation { get; set; }
    }
}
