//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_utilisation
    {
        public decimal id { get; set; }
        public System.DateTime asof_date { get; set; }
        public decimal category_id { get; set; }
        public Nullable<decimal> acquired { get; set; }
        public Nullable<decimal> unused { get; set; }
        public Nullable<decimal> wasted { get; set; }
        public string created_by { get; set; }
        public decimal location_id { get; set; }
    
        public virtual cnf_categories cnf_categories { get; set; }
        public virtual cnf_locations cnf_locations { get; set; }
        public virtual cnf_users cnf_users { get; set; }
    }
}
