//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_feedback
    {
        public System.DateTime time_stamp { get; set; }
        public string contact_no { get; set; }
        public string contact_email { get; set; }
        public Nullable<decimal> location_id { get; set; }
        public string feedback { get; set; }
        public string username { get; set; }
    }
}
